name: lykke_mobile_mavn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.16+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.24.1
  flutter_hooks: ^0.9.0
  provider: ^4.1.3
  dio: ^3.0.9
  equatable: ^1.1.0
  yaml: ^2.2.0
  intl: ^0.16.0
  flutter_secure_storage: ^3.3.1+1
  firebase_core: 0.4.5
  firebase_analytics: ^5.0.11
  firebase_remote_config: ^0.3.0+3
  firebase_dynamic_links: ^0.5.0+11
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.13
  shared_preferences: ^0.5.6+2
  recase: ^3.0.0
  flutter_svg: ^0.17.4
  camera: ^0.5.7+4
  auto_size_text: ^2.1.0
  path_provider: ^1.6.1
  flutter_native_image: ^0.0.5+2
  transparent_image: ^1.0.0
  flutter_image_compress: ^0.6.5+1
  native_device_orientation: ^0.3.0
  tuple: ^1.0.3
  dots_indicator: ^1.1.0
  flutter_sim_country_code: ^0.0.3
  qr_flutter: ^3.2.0
  url_launcher: ^5.4.2
  barcode_scan: ^2.0.1
  webview_flutter: ^0.3.19+8
  percent_indicator: ^2.1.1+1
  flutter_html: ^1.0.0
  decimal: ^0.3.5
  sms_autofill: ^1.2.0
  throttling: ^0.8.0
  app_settings: ^4.0.0
  package_info: ^0.4.0+14
  version: ^1.0.3
  store_redirect: ^1.0.2
  clipboard_manager: ^0.0.4
  flutter_styled_toast: ^1.2.1
  flutter_open_whatsapp: ^0.1.2
  local_auth: ^0.6.1+3
  google_maps_flutter: ^0.5.27+2
  location: ^3.0.0
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_gherkin: ^1.1.7+5
  mock_web_server: ^4.1.1
  mockito: ^4.1.1
  intl_translation: ^0.17.9
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FC7E78"
  adaptive_icon_foreground: "assets/app_icon.png"
# If you want to re-update the icons run these commands:
# 1. flutter pub get
# 2. flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunito-sans/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito-sans/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito-sans/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito-sans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito-sans/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito-sans/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito-sans/NunitoSans-Black.ttf
          weight: 900
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair-display/PlayfairDisplay-Black.ttf
          weight: 900